LPCIC/elpi

ELPI.md
bench/sources/chr.elpi
bench/sources/chrGCD.elpi
bench/sources/llamchr.elpi
src/elpi_API.ml
src/elpi_ast.ml
src/elpi_ast.mli
src/elpi_compiler.ml
src/elpi_data.ml
src/elpi_parser.ml
src/elpi_runtime.ml
src/elpi_util.ml
src/elpi_util.mli

From the user perspective:
- patterns operate on frozen terms
- two alignment mode
- auto for L\lambda
- manual:
- matched constraints are spread
- one chooses in which context the new goal is injected
- injection is manual
- less bugs, better error messages
Inside the engine:
- the new code is more clear
- but makes many passes on the terms to shift them correctly
- all UVar that intervene are expanded to level 0
- this may resume other goals that then would immediately
be suspended

CHR: new syntax and implementation

---

src/runtime.ml
src/runtime.mli
src/util.ml
src/util.mli
tests/sources/restriction4.elpi
tests/sources/restriction5.elpi
tests/sources/restriction6.elpi
tests/suite/correctness_HO.ml

This is mostly to make @sacerdot aware.
The commit history should be clear and I've added a test for each piece of code I've touched.
Note: the code containing "(*CSC: XXX why vardepth and not to_ ? *)" has been rewritten, and indeed we use `to_` all the time

Restriction bug

---

src/API.ml
src/API.mli
src/builtin.ml
src/data.ml
src/runtime.ml
src/runtime.mli

This simplifies the API by hiding an implementation detail.
Fix #38

API: flexible terms are at lvl 0

---

elpi_REPL.ml
src/API.ml
src/API.mli
src/builtin.ml
src/builtin.mli
src/data.ml
src/runtime.ml
src/runtime.mli
src/util.ml
src/util.mli

When converting arguments of a built in predicate depend on the
context of the program (hypotheses and constraints) we can now
provide a conversion function for the context that is run once
and forall and whose output is the passed to the conversion functions
of the arguments.
Limitation: for each built in only one context conversion function is
allowed.
Fix: #40

FFI: contextual conversion of arguments

---

.travis.yml
dune-project
elpi.opam
src/dune

When elpi is built in one opam switch then rebuilt in another, the build fails because dune does not know camlp5 has changed.
Test case:
```
$ opam switch 4.08
$ dune build
$ opam switch 4.10
$ dune build
-     ocamldep src/.elpi.objs/parser.pp.mli.d (exit 2)
- (cd _build/default && /home/opam/.opam/4.10.0+trunk/bin/ocamldep.opt -modules -intf src/parser.pp.mli) > _build/default/src/.elpi.objs/parser.pp.mli.d
- >> Fatal error: OCaml and preprocessor have incompatible versions
- Fatal error: exception Misc.Fatal_error
-     ocamldep src/.elpi.objs/parser.pp.ml.d (exit 2)
- (cd _build/default && /home/opam/.opam/4.10.0+trunk/bin/ocamldep.opt -modules -impl src/parser.pp.ml) > _build/default/src/.elpi.objs/parser.pp.ml.d
- >> Fatal error: OCaml and preprocessor have incompatible versions
- …
```

Avoid build failures when the camlp5 binary changes

---

ppxfindcache/ppxfindcache_aux.ml

ppxfindcache_aux.ml uses `sha1sum` which is fairly old and not available on Mac by default (it can be installed with homebrew or Macports). `shasum` is a replacement available on Mac, Linux (tested on Ubuntu 18.04) and Cygwin. Without additional options it should be identical to sha1sum.

Replace sha1sum with shasum in ppxfindcache_aux.ml

---

Makefile
elpi.opam
ppxfindcache/dune
src/dune

We make the ppx executables private and refer to them by a qualified
path. This allows us to rmeove a hack to edit the .install file after
dune generates it.

Remove .install file hack

---

CHANGES.md
src/.ppcache/API.ml
src/.ppcache/API.mli
src/.ppcache/compiler.ml
src/.ppcache/compiler.mli
src/.ppcache/data.ml
src/.ppcache/runtime_trace_off.ml
src/.ppcache/runtime_trace_on.ml
src/API.ml
src/API.mli
src/compiler.ml
src/compiler.mli
src/data.ml
src/runtime.ml

After time measuring in Coq-Elpi we found that "assembling + optimizing" a program can even 0.01 of a second, which is not much in the absolute can be 10x the execution time.
The main trick is to expose an API to compile a unit using the same, locked, symbol table of a program. In this way the unit is guaranteed to allocate no new symbols and can hence be assembled without relocating it.

speedup compiler

---

src/API.mli

Points to Elpi.Builtin instead of Elpi_builtin, and uses some document
syntax to pretty up the documentation.
Here's what the docs look like rendered with these changes: 
I'm not 100% the use of params is an improvement. Let me know if you'd rather I drop that and just fix the module reference.
I hope this superficial fix is not too presumptuous :)
I am so glad this library and interpreter exists :)

Improve init docs

---

CHANGES.md
src/builtin.elpi
src/builtin_stdlib.elpi

Currently, `nth` issues a single error message `nth run out of list items`, for a few situations:
- when the index is too large;
- when the index is negative;
- and when it successfully indexes the collection, but unifying this element with the result fails. (This is due to improper cut placement.)
This change keeps the error message for the first situation, but adds a `nth got a negative index` error message for the second, and makes it fail normally in the third case.

Improve behavior and error messages in nth

---

src/parser/error_messages.txt
src/parser/grammar.mly
src/parser/lexer.mll.in
src/parser/test_lexer.ml
src/parser/tokens.mly

This is a bit hackish as it modifies the lexer but I think it's ok.
If we decide to go for it, I should add tests and doc.

Make comma optional in predicate declarations

---

elpi.opam

(Seems) needed to match the changelogs in https://github.com/LPCIC/elpi/releases, assuming those are correct — haven't checked.

elpi.opam: depend on OCaml 4.08

---

elpi.opam
src/runtime.ml

The type definition for `alternatives` is a record, so a clever compiler (such as Flambda 2) can assume that values of this type can never be equal to `0`. This translates all `alts == noalts` checks into trivial `false` constants, eventually breaking down with a segfault when `noalts` is actually passed.
My proposed fix is the minimal one: hide the constant `0` from the compiler, so it can't optimise away.
The real fix is to use a variant definition. Example:
```ocaml
and alternative =
| Noalts
| Alts of {
cutto_alts : alternative;
program : prolog_prog;
adepth : int;
agoal_hd : constant;
ogoal_arg : term;
ogoal_args : term list;
agid : UUID.t; [@trace]
goals : goal list;
stack : frame;
trail : T.trail;
state : State.t;
clauses : clause list;
next : alternative;
}
```
It's exactly the …

Hide unsafe code from the optimiser

---

elpi.opam
src/elpi_trace_elaborator.ml
tests/sources/trace.elab.json
tests/sources/trace2.elab.json
tests/sources/trace_chr.elab.json
tests/sources/trace_findall.elab.json

Fix for yojson 2.0.2

---

src/trace_atd.ts

After running `dune build`, the workspace isn't clean. Fix this by running `dune build` and commiting.

Run dune build and check in modified files

---

elpi.opam
src/compiler.ml
src/runtime.ml
src/runtime.mli
tests/sources/dune
tests/sources/sepcomp_perf1.ml
tests/sources/sepcomp_perf2.ml
tests/sources/sepcomp_perf3.ml
tests/sources/sepcomp_perf4.ml
tests/suite/elpi_api.ml
tests/suite/elpi_api_performance.ml

improve separate compilation API performance

---

CHANGES.md
src/builtin.elpi
src/builtin_stdlib.elpi
tests/sources/trace_findall.elab.json
tests/sources/trace_findall.json

before:
```prolog
main :-
std.rev A B. % Here infinite loop
```
now: when $1^{st}$ arg of `std.rev` is flex, modes correctly prevents the loop

avoid infinite loop when calling rev with flex term

---

src/compiler.ml

While not crazy, with this trivial patch I get a non-negligible size reduction of `mathcomp/ssreflect/order.vo` from 11817893 bytes to 11087515 bytes (~6%).

Store symbol tables in a more compact way for compiled programs.

---

src/compiler.ml

Follow-up of #248, basically made of two units.
- Make the representation of the pruned symbol more compact by dropping useless data and representing the map as an array.
- Reduce the size of the Flat.program type by hoisting out data that is actually not semantically part of this record.
This reduces the size of order.vo from 11087515 bytes to 10349640 bytes, i.e. another compounded 6%.
EDIT: the last commit compacts this file even more, to 10062305 bytes.

More compact representation of compiled programs

---

src/runtime.ml
tests/sources/bug-256.elpi
tests/sources/llam.elpi
tests/sources/trace_w.json
tests/suite/correctness_HO.ml

The simplification step turns `X c0 c1` (that is `UVar(r,0,2)`) into `Y^2` via `X := a\b\Y^2`.
In #256 the query `pi x\ u (y\ X x y)` goes against `u (x\x)`. The simplification step was eating both arguments generating
`X := a\  b\ Y^1 a `. Now it instead generates `X := a\ Y^1`, so that we have `u (y\ Y^1 y) = u (y\y)` so `Y := x\x` and hence `X := a\b\b` that is correct.
The old code was confusing locally bound variables and pi generated ones in the simplification step that seems wrong.
By doing so, the old code was always eating all arguments, the 2 in `UVar(r,0,2)`, and the rest of the unification code was assuming that, after the simplification step, the term was either `UVar(_,_,0)` or `AppUVar`. The current patch restores that "a posteriori", but we should pre compute it or fix …

unification: fix simplification step

---

src/compiler.ml
tests/sources/typeabbrv13.elpi
tests/sources/typeabbrv14.elpi
tests/suite/correctness_FO.ml

```prolog
typeabbrev (dl A) (list A).
pred p i:dl (dl A).
```
`dl (dl A)` is no more considered as an invalid (looping) type.
A typeabbrev can be created only if all of the constants in it have already been declared before it.
Recursive typeabbrev (like `typeabbrev dl dl` are still forbidden)

[typeabbrev] type `dl (dl A)` where `dl` is typeabbrev is no more "looping"

---

src/parser/ast.ml

The term: `p :- (true, true), (true,true).` produces the ast:
```
(app
[const :-, const p, 
app [const ,, app [const ,, const true, const true], const true, const true]]), 
```
Note that we have the subterm `app [COMMA, app [COMMA, true, true], true, true]`
With this PR the compiler flattens the term and produces instead:
```
(app
[const :-, const p, 
app [const ,, const true, const true, const true, const true]), 
```
The same subterm is now: `app [COMMA, true, true, true, true]`

[compiler] flatten commas AST

---

tests/test.real.ml

Running the command `make tests ONLY=IO_COLON`
gives this:
Note the message ``elpi/usr/bin/env: `lua5.1`...`` displayed after the execution of the test
I suppose the problem come from Sys.command in combination with `&> /dev/null`.
This PR aims to hide the message

[test.real] command_exist

---

src/runtime/discrimination_tree.ml
src/runtime/discrimination_tree.mli
src/runtime/runtime.ml
tests/sources/dt_var3.elpi
tests/suite/correctness_FO.ml

I have tested this change on all the project thanks to this change, where I put DTree
in all predicate with high indexing depth.
To perform the same test apply the following diff.
```diff
diff --git a/src/compiler/compiler.ml b/src/compiler/compiler.ml
index 983da7c7..e134e47e 100644
--- a/src/compiler/compiler.ml
+++ b/src/compiler/compiler.ml
@@ -512,13 +512,13 @@ end = struct (* {{{ *)
| Index(i,index_type) :: rest ->
let it =
match index_type with
-           | None -> None
-           | Some "Map" -> Some Map
-           | Some "Hash" -> Some HashMap
+           | None -> Some DiscriminationTree
+           | Some "Map" -> Some DiscriminationTree
+           | Some "Hash" -> Some DiscriminationTree
| Some "DTree" -> Some DiscriminationTree
| Some s -> error ~loc ("unknown indexing …
```

dt filter out uvar in input mode with rigid arg

---

src/compiler/compiler.ml
src/compiler/determinacy_checker.ml
src/compiler/type_checker.ml
src/runtime/data.ml
tests/sources/functionality/test109.elpi
tests/sources/functionality/test110.elpi
tests/sources/functionality/test111.elpi
tests/sources/functionality/test112.elpi
tests/sources/functionality/test113.elpi
tests/sources/functionality/test114.elpi
tests/suite/correctness_FO.ml

Performing a retroactive check on a rule that uses local clause loading and catchall
